name: Style

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v6
    
    - name: Install clang-format
      run: brew install llvm@17

    - name: configure
      run: |
        git config clangformat.binary "$(brew --prefix llvm@17)/bin/clang-format"
        "$(brew --prefix llvm@17)/bin/clang-format" --version
        cmake -Htest -Bbuild

    - name: check style
      run: cmake --build build --target check-format
